esphome:
    name: kids-bedroom-window-ac
    platform: ESP32
    board: esp32doit-devkit-v1
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret host_domain
  fast_connect: true
  power_save_mode: LIGHT

ota:
  password: !secret ota_password

api:
  password: !secret api_password

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: false
  discovery_object_id_generator: "device_name"
  discovery_unique_id_generator: mac

  # Disable logging over UART (required)
logger:
  baud_rate: 0
  level: WARN

# UART settings for Midea dongle (required)
uart:
  tx_pin: 1         # hardware dependant
  rx_pin: 3         # hardware dependant
  baud_rate: 9600

# Main settings
climate:
  - platform: midea
    name: Kid's Bedroom Window AC
    period: 1s                  # Optional
    timeout: 2s                 # Optional
    num_attempts: 3             # Optional
    autoconf: true              # Autoconfigure most options.
    beeper: false               # Beep on commands.
#    visual:                     # Optional. Example of visual settings override.
#      min_temperature: 60 °F    # min: 17
#      max_temperature: 86 °F    # max: 30
#      temperature_step: 1 °F    # min: 0.5
    custom_fan_modes:
      - SILENT
      - TURBO
    supported_swing_modes:
      - VERTICAL
    outdoor_temperature:        # Optional. Outdoor temperature sensor (may display incorrect values after long inactivity).
      name: Kid's Bedroom Outdoor Temp