esphome:
  name: sump-monitor
  platform: ESP32
  board: wemos_d1_mini32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret host_domain
  fast_connect: true
  power_save_mode: LIGHT

ota:
  num_attempts: 3
  password: !secret ota_password

api:
  encryption:
    key: !secret api_encryption_key
  password: !secret api_password

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: false
  discovery_object_id_generator: "device_name"
  discovery_unique_id_generator: mac

logger:
  level: INFO
  baud_rate: 0

# Vibration sensors
binary_sensor:
  - platform: gpio
    pin: 17
    name: "Sump Vibration"
    id: sump_vibration
    device_class: vibration
    filters:
    - delayed_on: 100ms
    - delayed_off: 1s
